<?php
/** @var \App\View\View $this */

$urlDel = $this->url(['controller' => 'user'], 'panel/delete');


echo $this->partial('user/header.phtml');
?>
<?php if(count($this->rows) > 0): ?>
<form method="post">
<table class="t-list">
	<thead>
		<tr>
			<th><input type="checkbox" /></th>
			<th class="col-name"><?= $this->translate('username') ?></th>
			<th><?= $this->translate('edit') ?></th>
			<th><?= $this->translate('delete') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->rows as $row): $urlEdit = $this->url(['id' => $row->id], 'panel/user-edit'); ?>
		<tr>
			<td>
				<label class="cb-box">
					<input type="checkbox" name="id[]" value="<?= $row->id ?>" />
				</label>
			</td>
			<th class="col-name"><a href="<?= $urlEdit ?>"><?= $row->username ?></a></th>
			<td><a href="<?= $urlEdit ?>"><span class="ico-box">&vellip;</span></a></td>
			<td>
				<button class="ico-box js-confirm" type="submit" name="id[]" value="<?= $row->id ?>"
					data-confirm="delete-confirm"
					formaction="<?= $urlDel ?>">
					&Cross;
				</button>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?= $this->security()->renderCSRFElement() ?>
</form>
<?php else: ?>
<h4>&mdash; <?= $this->translate('empty') ?> &mdash;</h4>
<?php endif; ?>